name: Go test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Generate templ files
        run: go tool templ generate

      - name: Build
        run: go build -v ./...

      - name: Test with the Go CLI
        run: go test ./... 
